Add alerts for volume/provider/device recovery states in DSS.
dcos/prometheus-alert-rules pull request #5
Opened 2019-05-21 11:21 UTC by nfnt

2019-05-21 11:27 UTC, bbannier requested changes

2019-05-21 11:27 UTC, bbannier commented on rules/dcos-storage.yml
> +    for: 1m
This time is too short to be useful; let's just remove the `for` clause.

Also below.

2019-05-21 11:29 UTC, bbannier approved these changes

2019-05-22 17:31 UTC, jieyu approved these changes

2019-05-22 17:31 UTC, merged